
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
kwejk_user:
    resource: "@KwejkUserBundle/Resources/config/routing.yml"
    prefix:   /

kwejk_admin:
    resource: "@KwejkAdminBundle/Resources/config/routing.yml"
    prefix:   /


kwejk_mems:
    resource: "@KwejkMemsBundle/Resources/config/routing.yml"
    prefix:   /